name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Run your CI checks (reuses ci.yml). If this fails, deploy won't run.
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build & upload artifact for Pages in one step.
      # The action auto-detects pnpm from your lockfile; you can also pin it.
      - name: Build with Astro
        uses: withastro/action@v4
        with:
          node-version: 22
          package-manager: pnpm@10.11.1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

